version: '3.8'
services: # 컨테이너
  db:
    image: mysql
    container_name: mysql-container2
    environment:
      MYSQL_ROOT_PASSWORD: alsgml610
      MYSQL_DATABASE: memo
    ports:
      - "3307:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-boot-app:
    image: board-image:latest
    container_name: board-container2
    ports:
      - "8081:8080"
    links:
      - db
    depends_on:
      - db #spring-boot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/memo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=alsgml610